name: Prettier Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    prettier-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install deps
              run: pnpm install --frozen-lockfile

            - name: Enable Prettier annotations
              run: echo "::add-matcher::.github/matchers/prettier-list-different.json"

            - name: Run Prettier check
              run: pnpm exec prettier --list-different .

            - name: Disable matcher
              if: always()
              run: echo "::remove-matcher owner=prettier-list-different::"
