name: Prettier Format

on:
    pull_request:
        branches: [main]

permissions:
    contents: write

jobs:
    format:
        runs-on: ubuntu-latest
        if: >
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
        steps:
            - name: Checkout PR HEAD
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install deps
              run: pnpm install --frozen-lockfile

            - name: Format code
              run: pnpm format

            - name: Commit formatting changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "style(*): auto-format code with Prettier"
                  branch: ${{ github.head_ref }}
